### ISSUE TITLE
Vanilla kernel URL is a dead link

### ISSUE THREAD

**Issue by maxgittelman** [SebNag/Personal_Wiki#1]
Hey,

Thank you for providing the the information for how to setup a patch for RT. On the following page Personal_Wiki/Linux/LinuxKernel/Patches/info.md there is a deadlink to retrieve the vanilla kernel. Would Linus Torvalds' github repo be the ideal replacement [link](https://github.com/torvalds/linux/tree/master/Documentation/admin-guide)?

**Comment by SebNag** [comment]
Ah thanks for pointing out. Indeed, the link was broken. It should have pointed to https://www.kernel.org/. 
However, I added the Link to the official Linux GitHub Repo too.
